[tool.poetry]
name = "dbtest"
version = "0.0.1"
description = ""
authors = [ "Alex Beverage" ]
packages = [{ include = "dbtest", from = "src" }]

[tool.poetry.dependencies]
python = "^3.12"
sqlalchemy = "^2.0.25"
asyncclick="8.1.7.2"
openai = "^1.12.0"
aiohttp = "^3.9.3"
asyncpg = "^0.29.0"
greenlet = "^3.0.3"
asyncio = "^3.4.3"
psycopg2 = "^2.9.9"
pylint = "^3.2.3"
backoff = "^2.2.1"
pytest = "^8.2.2"
fastapi = "^0.112.2"
uvicorn = "^0.30.6"

[tool.poetry.scripts]
dbtest = "dbtest.dbtest:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "INFO"
