[tool.poetry]
name = "lqconsole"
version = "0.0.1"
description = ""
authors = [ "Alex Beverage" ]
packages = [{ include = "lqconsole", from = "src" }]

[tool.poetry.dependencies]
python = "^3.13"
aiohttp = "^3.9.3"
asyncclick = "^8.1.7.2"
asyncpg = "^0.30.0"
backoff = "^2.2.1"
fastapi = "^0.112.2"
greenlet = "^3.0.3"
openai = "^1.81.0"
sqlalchemy = "^2.0.25"
uvicorn = "^0.30.6"
boto3 = "^1.38.22"

[tool.poetry.group.dev.dependencies]
pylint = "^3.2.3"
pytest = "^8.2.2"

[tool.poetry.scripts]
lqconsole = "lqconsole.lqconsole:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "INFO"
